# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX support
android.useAndroidX=true
android.enableJetifier=true

# Optimization
android.enablePngCrunchInReleaseBuilds=true

# Build a single "fat" APK for all common architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Architecture settings
newArchEnabled=false
hermesEnabled=true

# Expo settings
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false
